#!/bin/bash

#--------------------------------------- How to use it ------------------------------------------------------#
# this script will do few things
# 1. It creates an instance of socreboard class inside an environment
# 2. writes basic structure of monitor inside specified file 
# it takes some arguments 
# this script is written only for using from other scripts
# it should not be used from terminal 
#------------------------------------------------------------------------------------------------------------#

scoreboard_class=${1:-default_scb};
scoreboard_ins=${2:-default_scb_ins};
active=${3:-ACTIVE};
new_f='UVM_NEW';
build='UVM_'$active'_BUILD';
connect='UVM_'$active'_CONNECT';
env_file=${4:-default_env.sv};
shift;
destination=${4:-mydir};

# Make instance of the created scoreboard inside the given environment class
sed -i "/uvm_env/a $scoreboard_class $scoreboard_ins ;" $destination/$env_file

# Create instance of the scoreboard class inside build_phase of environment class 
sed -i "/$build/a $scoreboard_ins=$scoreboard_class::type_id::create(\"$scoreboard_ins\",this);" $destination/$env_file




cat << _EOF_

class $scoreboard_class extends uvm_scoreboard;

	\`uvm_component_utils($scoreboard_class)


	  function new(string name, uvm_component parent);
	    super.new(name,parent);
	  \`uvm_info(get_full_name(), "Inside UVM_NEW", UVM_LOW);
	  endfunction:new


	  virtual function void report();
	  \`uvm_info(get_full_name(), "Inside UVM_ACTIVE_REPORT", UVM_LOW);
	  endfunction: report



endclass:$scoreboard_class
_EOF_




#-------------------------------------------------- THE END ---------------------------------------------------------#