#!/bin/bash


#--------------------------------------- How to use it ------------------------------------------------------#
# this script will create a top level module inside specified file
# it takes name of interface file as the only argument
# example:
#        ./create_top intf.sv > file_name(top.sv) 
# file_name is name of the file where code will be written
#------------------------------------------------------------------------------------------------------------#

interface_file=${1:-default_intf.sv}

cat << _EOF_

\`include "$interface_file"

module top;

      import uvm_pkg::*;
      \`include "uvm_macros.svh"

      initial 
      begin

     	      
	      run_test();
	      
      end


endmodule


_EOF_






#-------------------------------------------------- THE END ---------------------------------------------------------#
