#!/bin/bash



#--------------------------------------- How to use it ------------------------------------------------------#
# this script will create a new sequence for a new testcase
# this script is written for using from terminal
# it can be used like any other script
#  ./script_name arg1 arg2 arg3 . . .
#------------------------------------------------------------------------------------------------------------#

extended=${1:-auto};
base_sequence_file=${2:-base_sequence.sv}
base_sequence=${3:-base_sequence}
parent_sequencer=${4:-auto_sequencer}
destination=${5:-mydir};
sequence_item=${6:-trans};


new_sequence_class="$extended""_sequence"
#new_sequencer_class="$extended""_sequencer"
#new_sequence_item_class="$extended""_trans"
#new_sequence_item_ins="$extended""_trans_ins"


$DIR/seq_override $base_sequence $new_sequence_class $parent_sequencer $sequence_item >> $destination/$base_sequence_file
