#!/bin/bash


#--------------------------------------- How to use it ---------------------------------------------------------------#
# this script will create an environment and lower classes(agent,scoreboard,subscriber etc.) based on given arguments
# this script is written only for using from other scripts
# it should not be used from terminal 
#---------------------------------------------------------------------------------------------------------------------#

virtual_sequencer_file=${1:-vsequencer.sv};
virtual_sequencer_class=${2:-vsequencer};
virtual_sequencer_ins=${3:-vsequencer_ins};
virtual_sequence_file=${4:-vsequence.sv};
virtual_sequence_class=${5:-default_vsequence};
virtual_sequence_ins=${6:-vsequence_ins};
subscriber_file=${7:-subscriber.sv};
subscriber_class=${8:-default_sbr};
subscriber_ins=${9:-default_sub_ins};
shift
scoreboard_file=${9:-scb.sv}
shift
scoreboard_class=${9:-default_scb};
shift
scoreboard_ins=${9:-default_scb_ins};
shift
scb_pkt=${9:-sent_pkt}
shift
scoreboard_port=${9:-scb_port};
shift
base_test_file=${9:-test_base.sv};
shift
env_file=${9:-default_env.sv};
shift
env_class=${9:-env};
shift
env_ins=${9:-env_ins};
shift
agent_file=${9:-default_agent.sv};
shift
agent_class=${9:-default_agent};
shift
agent_ins=${9:-default_agent_ins};
shift
agent_port=${9:-a_port};
shift
driver_file=${9:-driver.sv}
shift
driver_class=${9:-default_driver}
shift
driver_ins=${9:-driver}
shift
monitor_file=${9:-monitor.sv}
shift
monitor_class=${9:-default_monitor};
shift
monitor_ins=${9:-monitor};
shift
mon_port=${9:-mon_port};
shift
sequencer_file=${9:-sequencer.sv}
shift
sequencer_class=${9:-default_sequencer};
shift
sequencer_ins=${9:-sequencer};
shift
sequence_file=${9:-sequence.sv}
shift
sequence_class=${9:-default_sequence};
shift
sequence_ins=${9:-sequence_ins};
shift
sequence_item_file=${9:-sequence_item.sv}
shift
sequence_item_class=${9:-trans}
shift
sequence_item_ins=${9:-trans_ins}
shift
mon_active=${9:-PASSIVE};
shift
active=${9:-ACTIVE};
shift;
destination=${9:-mydir};









../scripts/do_agent $env_file $agent_file $agent_class $agent_ins $driver_file $driver_class $driver_ins $monitor_file $monitor_class $monitor_ins $agent_port $mon_port $sequencer_file $sequencer_class $sequencer_ins $sequence_file $sequence_class $sequence_ins $sequence_item_file $sequence_item_class $sequence_item_ins $virtual_sequencer_file $virtual_sequencer_class $virtual_sequence_file $virtual_sequence_class $mon_active $active $destination
../scripts/do_subscriber $subscriber_file $subscriber_class $subscriber_ins $sequence_item_class $env_file $agent_ins $agent_port $active $destination
../scripts/do_scoreboard $scoreboard_file $scoreboard_class $scoreboard_ins $scb_pkt $scoreboard_port $env_file $agent_ins $monitor_ins $mon_port $sequence_item_class $sequence_item_ins $active $destination
../scripts/create_vsequencer $virtual_sequencer_class $virtual_sequencer_ins $active $env_file $destination> $destination/$virtual_sequencer_file
../scripts/create_vsequence $virtual_sequence_class $virtual_sequence_ins $virtual_sequencer_class $virtual_sequencer_ins $base_test_file $env_class $env_ins $active $destination> $destination/$virtual_sequence_file























