#!/bin/bash
destination=$1;shift;
filename=$1;
sed -n -e  '/uvm_c/,$!p' $destination/$filename>$destination/temp1;
sed -n -e '/_active_/,$!p' $destination/temp1 > $destination/temp;

scoreboard_class=$(grep scb $destination/temp | cut -d ' ' -f 1) 
subscriber_class=$(grep sbr $destination/temp | cut -d ' ' -f 1)
agent_class=$(grep agent $destination/temp | cut -d ' ' -f 1)

scoreboard_ins=$(grep scb $destination/temp | cut -d ' ' -f 2) 
subscriber_ins=$(grep sbr $destination/temp | cut -d ' ' -f 2)
agent_ins=$(grep agent $destination/temp | cut -d ' ' -f 2)

count=1;
echo "************ scoreboard class ************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$scoreboard_class" 

count=1;
echo "************ scoreboard instance ************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$scoreboard_ins" 

count=1;
echo "************ subscriber class ***************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$subscriber_class" 

count=1;
echo "************ subscriber instance ************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$subscriber_ins" 

count=1;
echo "************ agent instance *****************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$agent_class" 

count=1;
echo "************ agent instance *****************"
while read line; do 
echo  --- $count ------ "$line" -------;count=$(($count+1)); done <<< "$agent_ins" 




