#!/bin/bash



#--------------------------------------- How to use it ------------------------------------------------------#
# this script will create a new sequence for a new testcase
# this script is written for using from terminal
# it can be used like any other script
#  ./script_name arg1 arg2 arg3 . . .
#------------------------------------------------------------------------------------------------------------#

extended=${1:-auto};
new_sequence_file=${2:-new_sequence.sv}
base_sequence=${3:-base_sequence}
destination=${4:-mydir};



new_sequence_class="$extended""_sequence"
new_sequencer_class="$extended""_sequencer"
new_sequence_item_class="$extended""_trans"
new_sequence_item_ins="$extended""_trans_ins"


./seq_override $base_sequence $new_sequence_class $new_sequencer_class $new_sequence_item_class $new_sequence_item_ins > $destination/$new_sequence_file
