#!/bin/bash

#--------------------------------------- How to use it ----------------------------------------------#
# this script will create a new test class                                                           #
# To use it three arguments have to passed in terminal                                               # 
# 1. name of test class                                                                              #
# 2. name of olde sequence class that has to be overridden                                           #
# 3. name of new sequence class                                                                      #
# example :                                                                                          # 
#         ./add_test new_test old_seq new_seq > file_name                                            #
# here, file_name is the file where the code has to be written                                       #
#----------------------------------------------------------------------------------------------------#

test_name=${1:-test_case}
old_sequence_class=${2:-old_seq};
new_sequence_class=${3:-new_seq};







cat << _EOF_
class $test_name extends uvm_test;

    \`uvm_component_utils($test_name)
    



    	function new(string name, uvm_component parent=null);
		super.new(name, parent);
		\`uvm_info(get_full_name(), "In  UVM_ACTIVE_NEW", UVM_LOW);

	endfunction : new




	virtual function void build_phase(uvm_phase phase);
		super.build_phase(phase);
		\`uvm_info(get_full_name(), "In  UVM_ACTIVE_BUILD", UVM_LOW);
	endfunction : build_phase
    




	virtual task run_phase(uvm_phase phase);
		super.run_phase(phase);
		
		phase.raise_objection(this, "Objection raise");
	      \`uvm_info(get_full_name(), "In  UVM_ACTIVE_RUN", UVM_LOW);


		$old_sequence_class::type_id::set_type_override($new_sequence_class::get_type());  

		phase.drop_objection(this, "Objection_drop");
	endtask : run_phase
	



endclass : $test_name

_EOF_

#-------------------------------------------------- THE END ------------------------------------------#