#!/bin/bash


#--------------------------------------- How to use it ------------------------------------------------------#
# this script will create a top level module inside specified file
# it takes name of interface file as the only argument
# example:
#        ./create_top intf.sv > file_name(top.sv) 
# file_name is name of the file where code will be written
#------------------------------------------------------------------------------------------------------------#

interface_file=${1:-default_intf.sv}



cat << _EOF_

\`include "uvm_pkg.sv" 
\`include "$interface_file"

module top;

      import uvm_pkg::*;


      initial 
      begin

      \`uvm_info(get_full_name(), "In  UVM_ACTIVE_RUN", UVM_LOW);
	      
	      run_test();
	      
      end


endmodule


_EOF_






#-------------------------------------------------- THE END ---------------------------------------------------------#