#!/bin/bash



#--------------------------------------- How to use it ------------------------------------------------------#
# this script will create whole testbench
# this script is written for using from terminal
# it can be used like any other script
#  ./script_name arg1 arg2 arg3 . . .
#------------------------------------------------------------------------------------------------------------#

common=${1:-auto};
top_file=${2:-top.sv}
destination=${3:-mydir};
base_test_file=${4:-base_test.sv};
test_name=${5:-base_test};
interface_file=$6;
interface_class=$7;
active=${8:-ACTIVE};
mon_active=${9:-PASSIVE};
interface_file=$common'_intf.sv'
interface_class=$common'_intf'
mkdir $destination




../scripts/create_interface $interface_class > $destination/$interface_file  
../scripts/create_top $interface_file > $destination/$top_file
../scripts/create_test_base $test_name > $destination/$base_test_file
../scripts/env_generate $common $base_test_file $destination $active $mon_active   

echo "Connect Interface using ./connect_interface and ./import_interface"  

